---
- name: show bbb_secret
  debug:
    var: hostvars[item]['ansible_facts']['ansible_local']['bbb_secret']
  when: not scalelite.no_log | bool

- name: show bbb_hostname
  debug:
    var: hostvars[item]['bbb_hostname']
  when: not scalelite.no_log | bool

- name: add bbb server to cluster
  block:
    - name: print bbb
      debug:
        var: hostvars[item]['ansible_facts']['ansible_local']['bbb_secret']
  no_log: not scalelite.no_log
