---
- name: get bbb_secret
  set_fact:
    _bbb_secret: "{{ hostvars[item]['ansible_facts']['ansible_local']['bbb_secret'] | string }}"

- name: get bbb_hostname
  set_fact:
    _bbb_hostname: "{{ hostvars[item]['bbb_hostname'] | string }}"

# we should check if our nodes are present in _current_bbb_nodes

- name: add bbb server "{{ _bbb_hostname }}" to cluster
  become: true
  become_user: "{{ scalelite.user }}"
  command: "bin/rake servers:add[https://{{ _bbb_hostname }}/bigbluebutton/api,{{ _bbb_secret }}]"
  args:
    chdir: "{{ scalelite.homepath }}/scalelite-git"
  register: _add_bbb_server
  no_log: scalelite.no_log
  changed_when: false

- name: parse enable server id
  set_fact:
    _confirm_bbb: "{{ _add_bbb_server.stdout_lines[1] | regex_replace( 'id:' ) | regex_replace( ' ' ) | string }}"

- name: enable bbb server in cluster
  become: true
  become_user: "{{ scalelite.user }}"
  command: "bin/rake servers:enable[{{ _confirm_bbb }}]"
  args:
    chdir: "{{ scalelite.homepath }}/scalelite-git"
  register: _enable_bbb_server
  no_log: scalelite.no_log
  changed_when: false
