---
- name: get bbb_secret
  set_fact:
    _bbb_secret: "{{ ansible_local[item]['bbb']['secret'] | string }}"

- debug: var=_bbb_secret

- name: get bbb_hostname
  set_fact:
    _bbb_hostname: "{{ ansible_local[item]['bbb']['hostname'] | string }}"

- name: make sure  bbb server "{{ _bbb_hostname }}" is part of the cluster
  become: true
  become_user: "{{ scalelite.user }}"
  command: "set -o allexport; source .env; set +o allexport; bin/rake servers:add[https://{{ _bbb_hostname }}/bigbluebutton/api,{{ _bbb_secret }}]"
  args:
    chdir: "{{ scalelite.homepath }}/scalelite-git"
  register: _add_bbb_server
  no_log: scalelite.no_log
  changed_when: false
  when: "_bbb_hostname not in _current_bbb_nodes.stdout"

- name: parse enable server id
  set_fact:
    _confirm_bbb: "{{ _add_bbb_server.stdout_lines[1] | regex_replace( 'id:' ) | regex_replace( ' ' ) | string }}"
  when: "_bbb_hostname not in _current_bbb_nodes.stdout"

- name: enable bbb server "{{ _bbb_hostname }}" in cluster
  become: true
  become_user: "{{ scalelite.user }}"
  command: "set -o allexport; source .env; set +o allexport; bin/rake servers:enable[{{ _confirm_bbb }}]"
  args:
    chdir: "{{ scalelite.homepath }}/scalelite-git"
  register: _enable_bbb_server
  no_log: scalelite.no_log
  changed_when: false
  when: "_bbb_hostname not in _current_bbb_nodes.stdout"
  # maybe we should create a option to enable/disable bbb servers here... -> TODO

- name: Ensure new servers are instantly polled
  become: true
  become_user: "{{ scalelite.user }}"
  command: "set -o allexport; source .env; set +o allexport; bundle exec bin/rake poll:all"
  args:
    chdir: "{{ scalelite.homepath }}/scalelite-git"
  when: "_bbb_hostname not in _current_bbb_nodes.stdout"
