---
- name: get bbb_hostname
  set_fact:
    _bbb_hostname: "{{ hostvars[item]['bbb_hostname'] | string }}"
  when: ansible_local[item]['bbb']['hostname'] is not defined

- name: get bbb secret via 'bbb-conf --secret'
  become: true
  command: bbb-conf --secret
  register: _bbb_config_output
  changed_when: false
  delegate_to: "{{ _bbb_hostname }}"
  when: ansible_local[item]['bbb']['secret'] is not defined

- name: parse bbb secret from output
  set_fact:
    _bbb_secret: "{{ _bbb_config_output.stdout |  regex_search('Secret: ([a-zA-Z0-9]*)', multiline=True) |  regex_replace('Secret: ') }}"
  when: ansible_local[item]['bbb']['secret'] is not defined

- name: Create fact directory
  become: true
  file:
    path: /etc/ansible/facts.d/
    state: directory
    owner: root
    group: root
  when: ansible_local[item]['bbb']['secret'] is not defined

- name: Create a static custom fact bbb_secret for "{{ _bbb_hostname }}"
  become: true
  template:
    src: templates/bbb.fact.j2
    dest: "/etc/ansible/facts.d/{{ item }}.fact"
    backup: true
    owner: root
    group: root
    mode: 0600
  when: ansible_local[item]['bbb']['secret'] is not defined

- name: read facts after adding custom fact
  setup: filter=ansible_local
  when: ansible_local[item]['bbb']['secret'] is not defined
