---
- name: get bbb_hostname
  set_fact:
    _bbb_hostname: "{{ hostvars[item]['bbb_hostname'] | string }}"

- name: get bbb secret via 'bbb-conf --secret'
  become: true
  command: bbb-conf --secret
  register: _bbb_config_output
  changed_when: false
  delegate_to: "{{ _bbb_hostname }}"

- name: parse bbb secret from output
  set_fact:
    _bbb_secret: "{{ _bbb_config_output.stdout |  regex_search('Secret: ([a-zA-Z0-9]*)', multiline=True) |  regex_replace('Secret: ') }}"

- name: Create fact directory
  become: true
  file:
    path: /etc/ansible/facts.d/
    state: directory
    owner: root
    group: root
  delegate_to: "{{ _bbb_hostname }}"

- name: Create a static custom fact bbb_secret for "{{ _bbb_hostname }}"
  become: true
  copy:
    content: "{{ _bbb_secret }}"
    dest: /etc/ansible/facts.d/bbb_secret.fact
    backup: true
    owner: root
    group: root
    mode: 0600
  delegate_to: "{{ _bbb_hostname }}"
