---
- name: combine scalelite configuration
  set_fact:
    scalelite: "{{ _scalelite|combine(scalelite, recursive=True) }}"

- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- include_role:
    name: geerlingguy.ruby

- include_role:
    name: geerlingguy.postgresql

- include_tasks: packages.yml

- include_tasks: user.yml

- include_tasks: secrets.yml

- name: clone scalelite git
  become: true
  become_user: "{{ scalelite.user }}"
  git:
    repo: "{{ scalelite.git_repo }}"
    version: "{{ scalelite.git_branch }}"
    dest: "{{ scalelite.homepath }}/scalelite-git"

- include_tasks: ruby.yml

- include_tasks: redis.yml

- include_tasks: systemd.yml

- include_tasks: cluster-status.yml

- include_tasks: get_bbb_secret.yml
  when: scalelite.configure_scalelite | bool
  with_items:
    - "{{ groups.bbb }}"

- include_tasks: cluster-configure.yml
  when: scalelite.configure_scalelite | bool
  with_items:
    - "{{ groups.bbb }}"

- include_tasks: cluster-status.yml
  when: scalelite.configure_scalelite | bool

- include_tasks: nginx-letsencrypt.yml
  when: scalelite.use_letsencrypt | bool

- include_tasks: nginx.yml
  when: scalelite.configure_nginx | bool

- set_fact:
    lb_secret: "{{ scalelite_loadbalancer_secret }}"
    lb_url: "https://{{ scalelite.hostname }}/bigbluebutton"

- import_role:
    name: greenlight
  when: scalelite.greenlight_enable | bool
