---
- name: combine scalelite configuration
  set_fact:
    scalelite: "{{ _scalelite|combine(scalelite, recursive=True) }}"

- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- include_role:
    name: geerlingguy.ruby
  vars:
    ruby_version: "{{ scalelite.ruby_version }}"
    ruby_install_from_source: "{{ scalelite.ruby_install_from_source }}"
    ruby_download_url: "{{ scalelite.ruby_download_url }}"

- include_role:
    name: geerlingguy.postgresql
  vars:
    postgresql_databases:
      - name: "{{ scalelite.psql_db }}"
        owner: "{{ scalelite.psql_user }}"
        encoding: 'unicode'
    postgresql_users:
      - name: "{{ scalelite.psql_user }}"
        password: "{{ scalelite.psql_pwd }}"
    postgres_users_no_log: "{{ scalelite.no_log }}"


- include_tasks: packages.yml

- include_tasks: user.yml

- name: clone scalelite git
  become: true
  become_user: "{{ scalelite.user }}"
  git:
    repo: "{{ scalelite.git_repo }}"
    version: "{{ scalelite.git_branch }}"
    dest: "{{ scalelite.homepath }}/scalelite-git"

- include_tasks: ruby.yml

- include_tasks: redis.yml

- include_tasks: systemd.yml

- include_tasks: cluster-status.yml

- include_tasks: cluster-configure.yml
  when: scalelite.configure_scalelite | bool
  with_items:
    - "{{ groups.bbb }}"
