---
- name: combine scalelite configuration
  set_fact:
    ranger: "{{ _scalelite|combine(scalelite, recursive=True) }}"

- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- include_tasks: packages.yml
