---
- name: combine scalelite configuration
  set_fact:
    scalelite: "{{ _scalelite|combine(scalelite, recursive=True) }}"

- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- include_tasks: packages.yml

- include_tasks: user.yml

- name: clone scalelite git
  become: true
  git:
    repo: "{{ scalelite.git_repo }}"
    version: "{{ scalelite.git_branch }}"
    dest: "{{ scalelite.homepath }}/scalelite-git"

- include_tasks: ruby.yml
