---
- name: create needed folders
  become: true
  file:
    path: "{{ item }}"
    state: directory
    group: root
    owner: root
  with_items:
    - /etc/nginx/ssl
    - /var/bigbluebutton
    - /var/bigbluebutton/published

- name: Generate DH Parameters with a different size (4096 bits)
  become: true
  openssl_dhparam:
    path: /etc/nginx/ssl/dhp-4096.pem
    size: 4096
  notify: systemctl restart nginx.service
  when: scalelite.nginx_dh | bool

- name: copy scalelite nginx conf
  become: true
  template:
     src: templates/nginx-scalelite.conf.j2
     dest: /etc/nginx/sites-available/scalelite.conf
     group: root
     owner: root
  notify: systemctl restart nginx.service

- name: Create a symbolic link
  become: true
  file:
    src: /etc/nginx/sites-available/scalelite.conf
    dest: /etc/nginx/sites-enabled/scalelite
    group: root
    owner: root
    state: link
  notify: systemctl restart nginx.service

