---
- name: install redis server
  package:
    name: "{{ scalelite.redis_pkgs }}"
    state: "{{ scalelite.package_state }}"
  become: true

- name: 'run bin rake db:prepare'
  shell: bin/rake db:prepare
  args:
    executable: /bin/bash
    chdir: "{{ scalelite.homepath }}/scalelite-git"
  changed_when: False
  no_log: "{{ scalelite.no_log }}"
