---
- name: install redis server
  package:
    name: "{{ scalelite.redis_pkgs }}"
    state: "{{ scalelite.package_state }}"
  become: true

- name: Count scalelite database tables
  shell:
    cmd: "export PGPASSWORD='{{ scalelite.psql_pwd }}'; {{ _scalelite_custom_psql_cmd }}"
  check_mode: no
  changed_when: false
  register: scalelite_database_tablecount
  no_log: "{{ scalelite.no_log }}"

- name: Ensure database schema is loaded
  shell:
    chdir: "{{ scalelite.path }}"
    executable: /bin/bash
    cmd: "set -o allexport; source .env; set +o allexport; bundle exec rails db:schema:load"
  become: yes
  become_user: "{{ scalelite.user }}"
  when: scalelite_database_tablecount.stdout|int <= 1
  no_log: "{{ scalelite.no_log }}"
