---
- name: mkdir /etc/defaults/
  become: true
  file:
    path: /etc/defaults
    state: directory


- name: create /etc/gemrc
# not sure if this is needed
  become: true
  copy:
    src: files/gemrc
    dest: /etc/gemrc
    owner: root
    group: root
    mode: 0744

- name: install gem version "scalelite.bundler_version"
  become: true
#  become_user: "{{ scalelite.user }}"
#  -> install as root because as user was not working
  gem:
    name: bundler
    version: "{{ scalelite.bundler_version }}"
    user_install: false
    state: present

- name: Ensure bundle in is deployment mode
  command:
    cmd: bundle config set deployment 'true'
    chdir: "{{ scalelite.path }}"
    creates: "{{ scalelite.path }}/.bundle/config"
  become: yes
  become_user: "{{ scalelite.user }}"

- name: Ensure environment file for scalelite
  become: true
  template:
    src: templates/env.j2
    dest: "{{ item }}"
    owner: "{{ scalelite.user }}"
  with_items:
    - "{{ scalelite.path }}/.env"
    - "{{ scalelite.homepath }}/.env"
    - /etc/defaults/scalelite

# bundle config build.nokogiri --use-system-libraries
- name: bundle config build nokogiri
  changed_when: false
  shell:
    chdir: "{{ scalelite.path }}"
    executable: /bin/bash
    cmd: "source .env; RAILS_ENV={{ scalelite.rails_env }} bundle config cap production build.nokogiri --use-system-libraries"
  become: yes
  become_user: "{{ scalelite.user }}"

- name: install requirements from scalelite Gemfile
  become: true
  bundler:
    state: present
    exclude_groups: development:test
    chdir: "{{ scalelite.path }}"
    extra_args:
      RAILS_ENV: production

- name: fix permission issue because we build some ruby stuff globally
  become: true
  file:
    path: "{{ scalelite.path }}"
    owner: "{{ scalelite.user }}"
    group: "{{ scalelite.user }}"
    recurse: true

# we could have a permission problem here.
# We did build the ruby stuff as root.
# If you are a ruby expert or know how to do this as user, please help!
