---
- name: create /etc/gemrc
# not sure if this is needed
  become: true
  copy:
    src: files/gemrc
    dest: /etc/gemrc
    owner: root
    group: root
    mode: 0744

- name: install gem version "scalelite.bundler_version"
  become: true
#  become_user: "{{ scalelite.user }}"
#  -> install as root because as user was not working
  gem:
    name: bundler
    version: "{{ scalelite.bundler_version }}"
#    user_install: true
    user_install: false
    state: present

- name: Ensure bundle in is deployment mode
  command:
    cmd: bundle config set deployment 'true'
    chdir: "{{ scalelite.homepath }}/scalelite-git"
    creates: "{{ scalelite.homepath }}/scalelite-git/.bundle/config"
  become: yes
  become_user: "{{ scalelite.user }}"

- name: install requirements from scalelite Gemfile
  become: true
#  become_user: "{{ scalelite.user }}"
  bundler:
    state: present
    exclude_groups: development:test
    chdir: "{{ scalelite.homepath }}/scalelite-git"

- name: Ensure environment file for scalelite
  become: true
  template:
    src: templates/env.j2
    dest: "{{ scalelite.homepath }}/scalelite-git/.env"
  become_user: "{{ scalelite.user }}"

- name: fix permission issue because we build some ruby stuff globally
  become: true
  file:
    path: "{{ scalelite.homepath }}/scalelite-git"
    owner: "{{ scalelite.user }}"
    group: "{{ scalelite.user }}"
    recurse: true

# we could have a permission problem here.
# We did build the ruby stuff as root.
# If you are a ruby expert or know how to do this as user, please help!
