---
- name: create /etc/gemrc
# not sure if this is needed
  become: true
  copy:
    src: files/gemrc
    dest: /etc/gemrc
    owner: root
    group: root
    mode: 0744

- name: install gem version "scalelite.bundler_version"
  become: true
#  become_user: "{{ scalelite.user }}"
  gem:
    name: bundler
    version: "{{ scalelite.bundler_version }}"
#    user_install: true
    user_install: false
    state: present

- name: install requirements from scalelite Gemfile
  become: true
#  become_user: "{{ scalelite.user }}"
  bundler:
    state: present
    exclude_groups: development:test
    chdir: "{{ scalelite.homepath }}/scalelite-git"

- name: fix permission issue because we build some ruby stuff globally
  become: true
  file:
    path: "{{ scalelite.homepath }}/scalelite-git"
    owner: "{{ scalelite.user }}"
    group: "{{ scalelite.user }}"
    recurse: true

# we do have a permission problem here. If you are a ruby expert, please help!
