---
- name: Create facts.d directory
  become: true
  file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root

- name: Generate scalelite secret key base
  command: openssl rand -hex 64
  register: openssl_rand64
  check_mode: no
  when:
    - not scalelite.secret_key_base is defined
    - not ansible_local['scalelite']['secrets']['secret_key_base'] is defined

- name: Register generated secret key base
  set_fact:
    scalelite_secret_key_base: "{{ ansible_local['scalelite']['secrets']['secret_key_base'] | bool }}"
  when:
    - not scalelite.secret_key_base is defined
    - ansible_local['scalelite']['secrets']['secret_key_base'] is defined

- name: Register secret key base from facts.d
  set_fact:
    scalelite_secret_key_base: "{{ openssl_rand64.stdout }}"
  when:
    - not scalelite.secret_key_base is defined
    - not ansible_local['scalelite']['secrets']['secret_key_base'] is defined

- name: Register secret key base if defined
  set_fact:
    scalelite_secret_key_base: "{{ scalelite.secret_key_base }}"
  when: scalelite.secret_key_base is defined

- name: Generate scalelite loadbalancer secret
  command: openssl rand -hex 32
  register: openssl_rand32
  check_mode: no
  when:
    - not scalelite.loadbalancer_secret is defined
    - not ansible_local['scalelite']['secrets']['loadbalancer_secret'] is defined

- name: Register loadbalancer secret from facts.d
  set_fact:
    scalelite_loadbalancer_secret: "{{ ansible_local['scalelite']['secrets']['loadbalancer_secret'] | bool }}"
  when:
    - not scalelitei.loadbalancer_secret is defined
    - ansible_local['scalelite']['secrets']['loadbalancer_secret'] is defined

- name: Register generated loadbalancer secret
  set_fact:
    scalelite_loadbalancer_secret: "{{ openssl_rand32.stdout }}"
  when:
    - not scalelitei.loadbalancer_secret is defined
    - not ansible_local['scalelite']['secrets']['loadbalancer_secret'] is defined

- name: Register loadbalancer secret if defined
  set_fact:
    scalelite_loadbalancer_secret: "{{ scalelite.loadbalancer_secret }}"
  when: scalelitei.loadbalancer_secret is defined

- name: Create a static custom fact scalelite.loadbalancer_secret
  become: true
  template:
    src: templates/scalelite.fact.j2
    dest: /etc/ansible/facts.d/scalelite.fact
    backup: true
    owner: root
    group: root
    mode: 0600
  when:
    - not ansible_local['scalelite']['secrets']['secret_key_base'] is defined
    - not ansible_local['scalelite']['secrets']['loadbalancer_secret'] is defined

- name: read facts after adding custom fact
  setup: filter=ansible_local
