---
- name: Create facts.d directory
  become: true
  file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root

- name: Generate scalelite secret key base
  command: openssl rand -hex 64
  register: openssl_rand64
  check_mode: no
  when:
    - not scalelite.secret_key_base is defined

- name: Register secret key base
  set_fact:
    scalelite.secret_key_base: "{{ openssl_rand64.stdout }}"
  when: not scalelite.secret_key_base is defined

- name: Generate scalelite loadbalancer secret
  command: openssl rand -hex 32
  register: openssl_rand32
  check_mode: no
  when:
    - not scalelite.loadbalancer_secret is defined

- name: Register loadbalancer secret
  set_fact:
    scalelite.loadbalancer_secret: "{{ openssl_rand32.stdout }}"
  when: not scalelitei.loadbalancer_secret is defined

- name: Create a static custom fact scalelite.loadbalancer_secret
  become: true
  copy:
    src: templates/scalelite.fact.j2
    dest: /etc/ansible/facts.d/scalelite.fact
    backup: true
    owner: root
    group: root
    mode: 0600

